Penguin strategy pairs added
Snowball-Finance/protocol pull request #60
Opened 2021-10-06 18:13 UTC by AbigailTCameron

2021-11-07 10:05 UTC, timbotro commented
This branch was really old so i rebased it to latest master

2021-11-07 10:24 UTC, timbotro commented
All of the strategies are called PenguinStrategyAsset1Asset2 e.g. `PenguinStrategyPefiLink` which is not part of standard naming scheme. This will make the test logic quite brittle if we had to add a special case just for this one exchange type, as currently we expect it in the format `{ContractType}{Exchange}{Asset1}{Asset2}`

2021-11-07 10:26 UTC, timbotro commented on contracts/interfaces/masterchefIgloosv2.sol
> +import "../lib/ownable,sol";
typo on here

2021-11-07 10:28 UTC, timbotro commented on contracts/interfaces/masterchefIgloos.sol
> +import "../lib/ownable,sol";
typo on here

2021-11-07 10:30 UTC, timbotro commented on contracts/interfaces/igloomaster.sol
> +pragma solidity =0.8.6;
Is this right? Most of our codebase is 0.6.X and this is only an interface after all

2021-11-07 10:34 UTC, timbotro commented
Lots of compilation errors on this, probably typos. This branch needs a fixup before the next PR:
![image](https://user-images.githubusercontent.com/89510251/140641407-8e1d84c5-41c7-4d58-b108-b8fecedf368d.png)

2021-11-07 10:53 UTC, timbotro requested changes
Lots of compilation errors on this, probably typos. This branch needs a fixup before the next PR:
![image](https://user-images.githubusercontent.com/89510251/140642066-2c94ca1d-007e-4bed-aa13-cf148bdbb0b4.png)

2021-12-08 21:34 UTC, closed without merging

2021-12-08 21:35 UTC, bigwampa commented
no longer accurate/up-to-date